// Generated by Wrangler on Mon Sep 02 2024 12:46:03 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	ADMINISTRATOR_SECRET: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_CLIENT_SECRET: string;
	OAUTH_JWT_SECRET: string;
	GITHUB_ORG: string;
	DB: D1Database;
}
