// Generated by Wrangler on Mon Aug 26 2024 22:24:34 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	ADMINISTRATOR_SECRET: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	DB: D1Database;
}
