name: Publish python-markdown-extension to Pypi

on:
  push:
    branches:
      - master
    paths:
      - python-markdown-extension/**
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-markdown-extension
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: eifinger/setup-rye@v3
        name: Setup Rye
        with:
          enable-cache: true
          working-directory: python-markdown-extension
      - run: rye sync
        name: Install Dependencies
      - run: rye build
        name: Build Package
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package distributions to PyPI
        with:
          packages-dir: python-markdown-extension/dist/
