name: Publish python-markdown-extension to Pypi

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'python-markdown-extension/**'
  publish:
    name: Publish
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-markdown-extension
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: eifinger/setup-rye@v3
        name: Setup Rye
        with:
          enable-cache: true
          working-directory: python-markdown-extension
      - run: rye sync
        name: Install Dependencies
      - run: rye build
        name: Build Package
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package distributions to PyPI
        with:
          packages-dir: python-markdown-extension/dist/
  upload-artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-markdown-extension
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: eifinger/setup-rye@v3
        name: Setup Rye
        with:
          enable-cache: true
          working-directory: python-markdown-extension
      - run: rye sync
        name: Install Dependencies
      - run: rye build
        name: Build Package
      - uses: actions/upload-artifact@v2
        with:
          name: python-markdown-extension
          path: python-markdown-extension/dist/
