name: Publish frontend to npm

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Set Node.js 20.x
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
      - uses: borales/actions-yarn@v5
        name: Run install
        with:
          cmd: install
          dir: frontend
      - uses: borales/actions-yarn@v5
        name: Run build
        with:
          cmd: build
          dir: frontend
      - run: npm publish --provenance --access public
        name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  upload-artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Set Node.js 20.x
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        name: Run install
        with:
          cmd: install
          dir: frontend
      - uses: borales/actions-yarn@v5
        name: Run build
        with:
          cmd: build
          dir: frontend
      - uses: actions/upload-artifact@v4
        with:
          name: review
          path: frontend/dist/
